// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdt2n1vaJnn_boCy9iO79c9V7FxxqmJXU',
    appId: '1:1009512228925:web:1c72814e2008b49bfd6254',
    messagingSenderId: '1009512228925',
    projectId: 'flutterfirenotes-111a4',
    authDomain: 'flutterfirenotes-111a4.firebaseapp.com',
    storageBucket: 'flutterfirenotes-111a4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQ4EwocLLtEhOIT2MeRUbo8HCiH0Gpvkw',
    appId: '1:1009512228925:android:d320b8b19102e825fd6254',
    messagingSenderId: '1009512228925',
    projectId: 'flutterfirenotes-111a4',
    storageBucket: 'flutterfirenotes-111a4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSrWmMjMpfpVyXOd5vxclwEVFboywlAVM',
    appId: '1:1009512228925:ios:d464bb4a48c1a583fd6254',
    messagingSenderId: '1009512228925',
    projectId: 'flutterfirenotes-111a4',
    storageBucket: 'flutterfirenotes-111a4.appspot.com',
    iosClientId: '1009512228925-a6ldtjlq51kcrfe99jh64ab95tbekccm.apps.googleusercontent.com',
    iosBundleId: 'com.example.testFb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSrWmMjMpfpVyXOd5vxclwEVFboywlAVM',
    appId: '1:1009512228925:ios:d464bb4a48c1a583fd6254',
    messagingSenderId: '1009512228925',
    projectId: 'flutterfirenotes-111a4',
    storageBucket: 'flutterfirenotes-111a4.appspot.com',
    iosClientId: '1009512228925-a6ldtjlq51kcrfe99jh64ab95tbekccm.apps.googleusercontent.com',
    iosBundleId: 'com.example.testFb',
  );
}
